apiVersion: chaos-mesh.org/v1alpha1
kind: PodChaos
metadata:
  name: pod-failure-appointment
  namespace: default
spec:
  action: pod-failure
  mode: one
  selector:
    labelSelectors:
      "app": "api-gateway"
  duration: "30s"
