name: Deploy to AKS

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Azure CLI Login
      run: |
        echo "Logging into Azure using Service Principal..."
        az login --service-principal \
          --username ${{ secrets.AZURE_CLIENT_ID }} \
          --password ${{ secrets.AZURE_CLIENT_SECRET }} \
          --tenant ${{ secrets.AZURE_TENANT_ID }}

        echo "Setting subscription..."
        az account set --subscription ${{ secrets.AZURE_SUBSCRIPTION_ID }}

        echo "Getting AKS credentials..."
        az aks get-credentials --resource-group ${{ secrets.AKS_RESOURCE_GROUP }} --name ${{ secrets.AKS_CLUSTER_NAME }}

        echo "Listing AKS nodes..."
        kubectl get nodes

    - name: Install or Upgrade Linkerd
      run: |
        echo "1: Verificando si Linkerd ya está instalado en aks..."
        
        curl -sL https://run.linkerd.io/install | sh  
        export PATH=$PATH:/home/$(whoami)/.linkerd2/bin

        if ! kubectl get namespace linkerd > /dev/null 2>&1; then
          echo "Linkerd no encontrado. Instalando..."
          
          linkerd install --crds | kubectl apply -f -
          
          linkerd install | kubectl apply -f -
                    
          linkerd viz install | kubectl apply -f -
        else
          linkerd upgrade | kubectl apply -f -
        fi
        
        kubectl get deploy -o yaml | linkerd inject - | kubectl apply -f -

    - name: Install KEDA
      run: |
        helm repo add kedacore https://kedacore.github.io/charts
        helm repo update
        helm install keda kedacore/keda --namespace keda --create-namespace
        helm repo add prometheus-community https://prometheus-community.github.io/helm-charts
        helm repo update
        helm install prometheus prometheus-community/prometheus --namespace monitoring --create-namespace
        kubectl apply --server-side -f https://github.com/kedacore/keda/releases/download/v2.16.0/keda-2.16.0-crds.yaml
        kubectl apply -f k8s/ --recursive

